matrix:
  include:
    - language: objective-c
language: objective-c
osx_image: xcode9
xcode_sdk: iphonesimulator11.3
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone 7

branches:
  only:
    - master
    - first-tests

env:
  global:
    - NODE_VERSION=stable

cache: yarn

install:
  - brew update
  - sudo launchctl limit maxfiles 2048 unlimited
  - sudo ulimit -n 10000
  - brew tap wix/brew
  - brew install applesimutils
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

  - brew install yarn --without-node
  - npm install -g react-native-cli
  - npm install -g detox-cli
  - cd Example
  - yarn
  - cd ../test
  - yarn

script:
  - export PRODUCT_BUNDLE_IDENTIFIER="com.swmansion.rn_gesture_handler_example"
  - FORCE_BUNDLING=1 detox build --configuration ios.sim.debug
  - detox test --configuration ios.sim.debug --cleanup
