name: Test iOS build
on:
  pull_request:
    paths:
      - '.github/workflows/ios-build.yml'
      - 'RNGestureHandler.podspec'
      - 'apple/**'
      - 'Example/ios/**'
      - 'FabricExample/ios/**'
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    if: github.repository == 'software-mansion/react-native-gesture-handler'
    runs-on: macos-14
    strategy:
      matrix:
        working-directory: [example, FabricExample]
    concurrency:
      group: ios-${{ matrix.working-directory }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use latest stable Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install node dependencies
        working-directory: ${{ matrix.working-directory }}
        run: yarn
      - name: Install pods
        working-directory: ${{ matrix.working-directory }}/ios
        run: bundle install && NO_FLIPPER=1 bundle exec pod install
      - name: Build app
        working-directory: ${{ matrix.working-directory }}
        run: yarn ios --simulator=\"iPhone 14\" --mode Debug --verbose --terminal /bin/zsh
