name: Publish to GitHub Pages

on:
  push:
    branches:
      - "@akwasniewski/update-gh-pages-workflow"

jobs:
  publish:
    if: github.repository == 'software-mansion/react-native-gesture-handler'

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Generate docs
        run: >-
          git config --local user.email "action@github.com"
          && git config --local user.name "GitHub Action"
          && cd packages/docs-gesture-handler
          && yarn
          && yarn build

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/docs-gesture-handler/build
          branch: gh-pages-test
          token: ${{ secrets.GITHUB_TOKEN }}
