name: Build package and publish on npm
env:
  YARN_ENABLE_HARDENED_MODE: 0
on:
  pull_request:
  workflow_dispatch:

jobs:
  npm-build:
    if: github.repository == 'software-mansion/react-native-gesture-handler'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PACKAGE_NAME: PLACEHOLDER # Will be reassigned later on.
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/

      # Ensure npm 11.5.1 or later is installed for OIDC
      - name: Update npm
        run: npm install -g npm@latest

      - name: Install node dependencies
        run: yarn install --immutable

      - name: Build package
        id: build
        working-directory: packages/react-native-gesture-handler
        run: npm pack

      - name: Add package name to env
        working-directory: packages/react-native-gesture-handler
        run: echo "PACKAGE_NAME=$(ls -l | egrep -o "react-native-screens-(.*)(=?\.tgz)")" >> $GITHUB_ENV

      - name: Assert PACKAGE_NAME
        if: ${{ env.PACKAGE_NAME == 'PLACEHOLDER' }}
        run: exit 1 # This should never happen.

      - name: Upload npm package to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: './packages/react-native-gesture-handler/${{ env.PACKAGE_NAME }}'
