name: Publish stable release to npm
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Whether to perform a dry run of the publish.
        type: boolean
        default: true

jobs:
  npm-build:
    if: github.repository == 'software-mansion/react-native-gesture-handler'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # for OIDC
    steps:
      - name: Publish stable release
        uses: ./.github/actions/publish-npm-package
        with:
          is-commitly: false
          dry-run: ${{ inputs.dry-run }}
